# Generated by Django 3.1 on 2020-08-19 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telefono',
        ),
    ]
