# Generated by Django 3.1 on 2020-08-20 19:28

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('telefono', phone_field.models.PhoneField(blank=True, help_text='Numero telefonico de contacto', max_length=31)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_de_nacimiento', models.DateField()),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('direccion', models.CharField(max_length=250)),
                ('observacion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
