# Generated by Django 3.1 on 2020-09-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('telefono_emergencia', models.IntegerField(blank=True, null=True)),
                ('correo', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('descripccion', models.CharField(blank=True, max_length=500, null=True)),
                ('sexo', models.CharField(max_length=15)),
            ],
        ),
    ]
