# Generated by Django 3.1 on 2020-09-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='descripccion',
            new_name='descripcion',
        ),
    ]
