# Generated by Django 3.1 on 2020-09-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
