# Generated by Django 3.1 on 2020-09-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200903_0611'),
        ('users', '0005_auto_20200902_1924'),
    ]

    operations = [
    ]
