# Generated by Django 3.1 on 2020-09-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20200904_0445'),
        ('users', '0006_merge_20200904_0448'),
    ]

    operations = [
    ]
