# Generated by Django 3.1 on 2020-09-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20200904_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='descripcion',
            new_name='descripccion',
        ),
    ]
