# Generated by Django 3.1 on 2020-09-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20200914_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='descripcion',
            new_name='descripccion',
        ),
    ]
