# Generated by Django 3.1.1 on 2020-09-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0004_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10),
        ),
    ]
