# Generated by Django 3.1 on 2020-08-26 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('no_anotacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_cita', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
