# Generated by Django 3.1 on 2020-08-27 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
        ('anotacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='id_cita',
            field=models.ForeignKey(blank=True, db_column='id_cita', null=True, on_delete=django.db.models.deletion.CASCADE, to='cita.cita'),
        ),
    ]
