# Generated by Django 3.1 on 2020-09-03 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_auto_20200902_1920'),
        ('anotacion', '0002_auto_20200827_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='id_cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='cita.cita'),
        ),
    ]
